# example values

config:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
  webInterfacePath: /admin
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.lutherancathedral.ru/
      name: Cathedral
    - url: https://dombulgakova.ru/
      name: Bulgakov

server:
  port: 8080

spring:
  security:
    user:
      name: user
      password: 123
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillbox?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100